/** How long a window stays alive without a ping. The UI pings every 3 s, so three missed pings. */
export const WINDOW_TTL_MS = 9000;
/** How long after "open" was answered a second press still counts as "close" (the window is still starting up). */
export const OPENING_MS = 6000;
/** After a window says bye, its hello and pings are ignored for this long: one that was in flight must not bring it back. */
export const BYE_IGNORE_MS = 5000;

const WINDOW_ID = /^[A-Za-z0-9-]{1,64}$/;

/** A window id is generated by the UI: 1 to 64 characters of letters, digits and dashes. */
export function isWindowId(value: unknown): value is string {
  return typeof value === "string" && WINDOW_ID.test(value);
}

export type ToggleResult = { action: "open" } | { action: "close"; ids: string[] };

/**
 * Which Sidecr windows are open, so the open key can close them and at most one exists.
 * Pure state with the clock passed in; the server owns the one instance.
 */
export function createWindowRegistry() {
  const seen = new Map<string, number>();
  // Windows that were told to close and have not heard yet: the answer to their next hello or ping carries it.
  // This reaches a window whose event stream is gone, which a pushed "data: close" cannot.
  const closeRequested = new Set<string>();
  // id -> when it said bye.
  const left = new Map<string, number>();
  let openingAt: number | null = null;
  // A second press while a window was still launching (nothing alive yet): the window that arrives is told to close.
  // Holds the time of the launch it belongs to, so it expires with that opening marker.
  let closeOnArrivalOf: number | null = null;

  /** Drops windows past their time to live and returns the rest. */
  const alive = (now: number): string[] => {
    for (const [id, at] of seen) {
      if (now - at >= WINDOW_TTL_MS) {
        seen.delete(id);
        closeRequested.delete(id);
      }
    }
    return [...seen.keys()];
  };
  const opening = (now: number): boolean => openingAt !== null && now - openingAt < OPENING_MS;
  /** True while this id said bye less than BYE_IGNORE_MS ago. Old entries are dropped on every call. */
  const hasLeft = (id: string, now: number): boolean => {
    for (const [other, at] of left) if (now - at >= BYE_IGNORE_MS) left.delete(other);
    return left.has(id);
  };

  return {
    /**
     * Registers (or refreshes) a window and, since the window has arrived, ends the "opening" state.
     * Returns the OTHER alive windows: the newest one wins, so they are told to close.
     * A hello from an id that just said bye is ignored.
     */
    hello(id: string, now: number): string[] {
      if (hasLeft(id, now)) return [];
      const others = alive(now).filter((other) => other !== id);
      seen.set(id, now);
      openingAt = null;
      if (closeOnArrivalOf !== null) {
        if (now - closeOnArrivalOf < OPENING_MS) closeRequested.add(id); // its hello answer says close
        closeOnArrivalOf = null;
      }
      // The older windows are pushed a close by the server; flagging them also reaches one whose stream is gone.
      for (const other of others) closeRequested.add(other);
      return others;
    },
    /** Refreshes a window; an id the server has not seen (it restarted, or the window outlived its entry) is registered. */
    ping(id: string, now: number): void {
      if (hasLeft(id, now)) return;
      seen.set(id, now);
    },
    /**
     * Refreshes a window the registry already knows, and never registers a new one. The server calls it for a window
     * whose event stream is still connected: a minimised window has its timers throttled, so its pings can stop for
     * longer than the time to live while the window is open. A window that said bye stays gone.
     */
    keepAlive(id: string, now: number): void {
      if (seen.has(id)) seen.set(id, now);
    },
    /** A window that closed: gone at once, not after the time to live. The last one leaving also ends "opening". */
    bye(id: string, now: number): void {
      hasLeft(id, now); // prunes old tombstones
      seen.delete(id);
      closeRequested.delete(id);
      left.set(id, now);
      if (alive(now).length === 0) openingAt = null;
    },
    alive,
    size: (): number => seen.size,
    tombstones: (): number => left.size,
    /** "open" was answered and a window is on its way. */
    markOpening(now: number): void {
      openingAt = now;
    },
    /** True once if this window was told to close by a toggle and has not been told yet. */
    takeClose(id: string): boolean {
      return closeRequested.delete(id);
    },
    /** The open key: close what is open (or starting), else ask the caller to open a window. */
    toggle(now: number): ToggleResult {
      const ids = alive(now);
      if (ids.length > 0 || opening(now)) {
        if (ids.length === 0) closeOnArrivalOf = openingAt; // still launching: close it when it arrives
        openingAt = null;
        for (const id of ids) closeRequested.add(id);
        return { action: "close", ids };
      }
      openingAt = now;
      closeOnArrivalOf = null;
      return { action: "open" };
    },
  };
}
